### PR TITLE
More tweaks and support for Mate

### PR DESCRIPTION
**Pull request by hate-m-dollarsign**
I found out how I can apply the old button hover effect only for non-colored buttons. ;)
button

Also added support for Mate Desktop Environment:
mate

Hope you like it!

Best,
Justin

### CODE REVIEW

**Comment by hate-m-dollarsign** [comment]
Btw, should I include changes to generated code (gtk-contained.css) in my PRs?
I also noticed there is quite a bit of dead code. Better leave that to minimize diff to Adwaita, right?

**Comment by ddelabru** [comment]
@hate-m-dollarsign, thank you; I like these changes.

I think including changes in the generated CSS is preferable, so that end users who clone the repo because they just want to install the theme don't have to take the extra step to generate it. (I don't know if I've forgotten to do that myself in the past, but I think it's a good idea.) I think I'll leave this PR open so you can regenerate the CSS in your own branch; let me know when you've done that and I'll merge.

I don't know that we have to take great pains to minimize differences between Bluebird and Adwaita for the gtk3 theme now that gtk3 has reached a stable state, and any significant changes to the way GTK themes work are supposed to occur in gtk4 instead; I think the purpose of keeping the codebase for Greybird gtk3 close to Adwaita was to make it easier to changes that were occuring in gtk3, but that time seems to have passed. If we can positively identify dead code in the theme, I'm not opposed to removing it, but I'm not good at identifying it with any certainty. If you can make a case that some code is definitely not being used, please feel free to propose removing it (in a separate PR).

Maybe I'll have a go at blue headerbars again.

**Comment by hate-m-dollarsign** [comment]
@ddelabru Thanks, done.

There are spots where background-color is set, although the element already has a background-image that takes precedence (not sure if there are more specific cases somewhere else where the image is set to none so the color takes effect again). Then there is a lot of code for scrollbar buttons that we don't have. Or code that loads .png's for checkboxes and radio buttons that are overwritten later...

Yeah, but I know what you mean. I commented out some stuff and could not see a difference, but a lingering doubt or fear of rare corner cases that actually do need some of it remains.. ;)

I have some ideas for the headerbars, and a patch that removes the padding for titlebuttons again that I inadvertently added (inherited from button.flat). I'm not sure if I'll get around to that soon, and I don't want to step on your toes. I'll post it in the issue discussion later.

**Comment by ddelabru** [comment]
One "weird corner case" I encountered: the XFCE panel uses both `background-image` and `background-color`. I tried removing the `background-color` property, since I figured it was being overridden anyway, but it turned out that the version of the XFCE panel I was using at the time couldn't make use of the `background-image` property, so once I removed `background-color` it had a totally different color from the rest of the panel. But right now I'm using XFCE and the notification area seems to have a gradient background, so I guess this verson does use `background-image`. :man_shrugging:

**Pull request merged**
